##attach libraries
```{r}
library(tidyverse) #install.packages("tidyverse")
library(readxl)
library(here)
library(skimr) #install.packages('skimr')  
library(kableExtra) #install.packages('kableExtra')
```

## read in data
```{r}
lobsters <- read_xlsx(here("data/lobsters2.xlsx"), skip=4)

skimr::skim(lobsters)
```
# make a pivot table
```{r}
siteyear_summary <- lobsters %>%
    group_by(site, year) %>%
    summarize(count_by_siteyear = n(),
              mean_size_mm = sd(size_mm, na.rm = TRUE))
```

## make a pretty table
```{r}
siteyear_summary %>%
    kable()
```
There are now `r nrow(lobsters)` total lobsters included in this report

```{r}
siteyear_summary <- lobsters %>%
    group_by(site, year) %>%
    summarize(count_by_siteyear = n(),
              mean_size_mm = mean(size_mm, na.rm=TRUE),
              sd_size_mm = sd(size_mm, na.rm=TRUE),
              median_size_mm = median(size_mm, na.rm=TRUE))
```
#make a plot
```{r}
ggplot(data = siteyear_summary, aes(x = year, y = median_size_mm, color = site)) +
  geom_line()

ggsave(here("figures", "lobsters-line.png"))
```

